### ISSUE TITLE
Complication with Google Fit shows a wicked bar

### ISSUE THREAD

**Issue by egvimo** [seahorsepip/LineWatchFace#1]
The complication (Google Fit) shows a graphical error (wicked bar) when the target is reached and exceeded (see screenshot).

![android wear-screenshot](https://user-images.githubusercontent.com/5247100/34446707-a3522d4c-ecdd-11e7-85ea-02c0a253b76c.png)

**Comment by seahorsepip** [comment]
Fixed by merging PR-4
